### ISSUE TITLE
关于同一个Model指定多个dsn

### ISSUE THREAD

**Issue by gtspoon** [firzen/QeePHP#3]
Tim神，随着数据越来越多，数据库做了主从，在有一些数据读取的时候我会去到从库里读取数据（特别是报表），例如一个Model是   Order，我想在调用Order::find()的时候，指定dsn。在需要即时数据的时候，链接的是主库；在报表的时候，想链接到从库。

有什么好的方案呢？指点指点~

**Comment by firzen** [comment]
最近比较忙，暂时没办法细想，提供一个思路。使用mysqli适配器 是可以同时使用多个dsn 的

**Comment by gtspoon** [comment]
mysqli如何调用多个dsn？请指点一下，我想使用的是Order::find()之类的，而非QDB::getConn($dsn)这种

**Comment by firzen** [comment]
在Model define 里面增加配置项

``` php
'table_config' => array (
                'dsn_name' => 'dns2'
            ),
```

**Comment by gtspoon** [comment]
这个用法之前你有说过的，但如何指定第二个第三个dsn呢？在调用的时候又如何调用指定的dsn呢？

**Comment by firzen** [comment]
https://github.com/firzen/QeePHP/wiki/%E8%AF%BB%E5%86%99%E5%88%86%E7%A6%BB%E9%85%8D%E7%BD%AE
